Repository ReachFive/identity-ios-sdk, pull requests merged in 2019-08, with the labels that each got.

#15 Use BrightFutures
  IdentitySdkCore.podspec
  IdentitySdkCore/IdentitySdkCore.xcodeproj/project.pbxproj
  IdentitySdkCore/IdentitySdkCore/Classes/Provider.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFive.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveApi.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveError.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePassword.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveProfile.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveProviders.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/AccessTokenResponse.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/Address.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/AuthToken.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/ClientConfigResponse.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/Consent.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/Emails.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/LoginSummary.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/OpenIdUser.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/Profile.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/ProviderConfig.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/ProvidersConfigsResult.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/AuthCodeRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/LoginProviderRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/LoginRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/ProfileSignupRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/RequestPasswordResetRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/SignupRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/UpdateEmailRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/UpdatePasswordRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/VerifyPhoneNumberRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/utils/CustomField.swift
  IdentitySdkCore/IdentitySdkCore/Classes/utils/DataRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/utils/DictionaryEncodable.swift
  IdentitySdkCore/Podfile
  IdentitySdkCore/Podfile.lock
  IdentitySdkFacebook.podspec
  IdentitySdkFacebook/IdentitySdkFacebook/Classes/FacebookProvider.swift
  IdentitySdkFacebook/Podfile
  IdentitySdkFacebook/Podfile.lock
  IdentitySdkGoogle/IdentitySdkGoogle/Classes/GoogleProvider.swift
  IdentitySdkGoogle/Podfile.lock
  IdentitySdkWebView/IdentitySdkWebView/Classes/WebViewProvider.swift
  IdentitySdkWebView/Podfile.lock
  Sandbox/Podfile
  Sandbox/Podfile.lock
  Sandbox/Sandbox/LoginController.swift
  Sandbox/Sandbox/ProfileController.swift
  Sandbox/Sandbox/SignupController.swift
Labels: require review

#17 Update Phone Number
  IdentitySdkCore/IdentitySdkCore.xcodeproj/project.pbxproj
  IdentitySdkCore/IdentitySdkCore/Classes/Provider.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveApi.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveProfile.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/AuthToken.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/UpdatePhoneNumberRequest.swift
  IdentitySdkFacebook/IdentitySdkFacebook/Classes/FacebookProvider.swift
  IdentitySdkGoogle/IdentitySdkGoogle/Classes/GoogleProvider.swift
  IdentitySdkWebView/IdentitySdkWebView/Classes/WebViewProvider.swift
  Sandbox/Sandbox.xcodeproj/project.pbxproj
  Sandbox/Sandbox/Base.lproj/Main.storyboard
  Sandbox/Sandbox/LoginController.swift
  Sandbox/Sandbox/ProfileController.swift
  Sandbox/Sandbox/UpdatePhoneNumberController.swift
Labels: feature

#29 Provider clientId optional
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveProviders.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/ProviderConfig.swift
Labels: require review

#31 Update README.md
  README.md
Labels: feature

#30 Fix password update
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveProfile.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/UpdatePasswordRequest.swift
Labels: require review

#32 Remove the `signedUid` attribute from the profile
  IdentitySdkCore/IdentitySdkCore/Classes/models/Profile.swift
Labels: fix
