Repository ReachFive/identity-ios-sdk, pull requests merged in 2020-06, with the labels that each got.

#60 Passwordless redirect_uri param configurable
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePasswordLess.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/StartPasswordlessRequest.swift
  Sandbox/Podfile.lock
  Sandbox/Sandbox/PasswordlessController.swift
Labels: feature, require review

#61 Passwordless verify redirect_uri param configurable
  .gitignore
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePasswordLess.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/VerifyAuthCodeRequest.swift
  Sandbox/Sandbox/Base.lproj/Main.storyboard
  Sandbox/Sandbox/PasswordlessController.swift
  Sandbox/Sandbox/UpdatePasswordController.swift
Labels: feature, require review

#59 fix: remove unused config value
  IdentitySdkCore/IdentitySdkCore/Classes/models/ProviderConfig.swift
Labels: feature

#62 Configure scheme with client ID
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFive.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePasswordLess.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFiveProviders.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/SdkConfig.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/AuthCodeRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/RefreshRequest.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/requests/VerifyAuthCodeRequest.swift
  IdentitySdkWebView/IdentitySdkWebView/Classes/WebViewProvider.swift
  README.md
  Sandbox/Sandbox/AppDelegate.swift
  Sandbox/Sandbox/Base.lproj/Main.storyboard
  Sandbox/Sandbox/Info.plist
  Sandbox/Sandbox/PasswordlessController.swift
Labels: feature, require review

#64 5.3.0
  CHANGELOG.md
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFive.swift
  IdentitySdkCore/IdentitySdkCore/Classes/ReachFivePasswordLess.swift
  IdentitySdkCore/IdentitySdkCore/Classes/models/SdkConfig.swift
  IdentitySdkCore/Podfile.lock
  IdentitySdkFacebook/Podfile.lock
  IdentitySdkGoogle/Podfile.lock
  IdentitySdkWebView/IdentitySdkWebView/Classes/WebViewProvider.swift
  IdentitySdkWebView/Podfile.lock
  Sandbox/Podfile.lock
  Sandbox/Sandbox/AppDelegate.swift
  version.rb
Labels: release

#65 Release v5.3.1
  CHANGELOG.md
  IdentitySdkWebView/IdentitySdkWebView/Classes/WebViewProvider.swift
  version.rb
Labels: release

#66 Release v5.3.2
  CHANGELOG.md
  README.md
  version.rb
Labels: release
